### ISSUE TITLE
Interface não comunica que os dados considerados são de 2013 até hoje

### ISSUE THREAD

**Issue by nazareno** [luizaugustomm/diferentonas-client#10]
Usamos os totais de convênios que iniciaram de 2013 até hoje, e isso não está dito na interface.

**Comment by luizaugustomm** [comment]
Em alguma versão anterior, esse dado estava sendo mostrado. Não seria o caso de voltar a exibi-lo nos cards de iniciativas?

**Comment by nazareno** [comment]
Isso é verdade para os dados do sistema inteiros. Só mostramos iniciativas
que começaram após 2013.

**Comment by jeffersonrpn** [comment]
Eu acho que a tela de pesquisa tem bastante espaço para colocar essa observação. Como é uma informação referente a todas as informações, e não só a uma tela específica, deveria ficar na página inicial.

**Comment by Iararibeiro** [comment]
Acho que poderia aparecer na tela da cidade, vou mostrar um exemplo.

**Comment by Iararibeiro** [comment]
![screenshot from 2016-06-16 17-37-06](https://cloud.githubusercontent.com/assets/3472291/16132401/4c0a4dac-33e9-11e6-8ed5-b164fad4348d.png)
![screenshot from 2016-06-16 17-37-56](https://cloud.githubusercontent.com/assets/3472291/16132402/4c0d3c7e-33e9-11e6-9525-6ed3336a05d2.png)

**Comment by luizaugustomm** [comment]
Gostei dessa versão entre parênteses. 🙂

**Comment by nazareno** [comment]
Não sei... eu acho que é importante ter essa explicação e outras (dados de
convênios e tal), mas que não é tão importante pra aparecer sempre. Que tal
um botão de mais informação, de interrogação ou algo assim?

**Comment by Iararibeiro** [comment]
Não sei, o botão pode ser que ninguém veja....Mas pode ser uma boa para solucionar a exposição de outras informações. Onde ficaria melhor esse botão??

**Comment by luizaugustomm** [comment]
Pessoal, eu coloquei a informação do ano de cada convênio nos cards de iniciativa. Será que resolve esse problema?

Eu fiz isso porque achei uma cidade (Caiçara-PB) que tinha duas iniciativas com o mesmo título e status. Aí, quando fui investigar, elas foram feitas em anos diferentes. Vocês concordam em deixar a informação do ano no card da iniciativa?

**Comment by nazareno** [comment]
eu concordo, mas é bom deixar claro se é o ano de assinatura, de início, ou
o que.

e isso é relacionado com a issue, mas não é a mesma coisa. acho que essa
informação de "os dados são apenas de convênios e apenas de 2013 pra cá"
deveria estar em algum '?' ou 'sobre' no app. que tal?

**Comment by luizaugustomm** [comment]
Concordo, Naza. Temos que ter um botão '?' com informações como essa.

**Comment by ricardoas** [comment]
Onde esse botão vai ficar? Perdi essa discussão... :(

**Comment by nazareno** [comment]
A ideia atual é na página que tem perfil do usuário e botão para sair.
Teremos lá ajuda e sobre.

**Comment by Iararibeiro** [comment]
@luizaugustomm @nazareno Adicionei essa informação no Ajuda.
