### ISSUE TITLE
Barra de pesquisa em cima da barra de notificações do celular

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#20]
Quando eu testei o app no celular, percebi que quando a barra de pesquisa sobe, ela fica sobrescrevendo parte do menu de notificações do celular.

**Comment by ricardoas** [comment]
Acontece no iOS tbm...
![search](https://cloud.githubusercontent.com/assets/311029/15870318/3e6ee920-2cc6-11e6-9911-286fffdc768e.png)

**Comment by jeffersonrpn** [comment]
O espaçamento está fixo agora, não mais em porcentagem.
