### ISSUE TITLE
Deixar a barra de pesquisas fixa e cidades pesquisadas abaixo

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#21]
Existem vários problemas porque a barra de pesquisa sobe quando pesquisamos uma cidade.

Que tal a gente deixar a barra fixa no quadrante superior do aplicativo e deixarmos o espaço inferior para colocarmos um atalho com as últimas cidades pesquisadas, para que o usuário possa selecioná-las sem precisar pesquisá-las de novo?

**Comment by nazareno** [comment]
Quais os problemas que existem?

**Comment by luizaugustomm** [comment]
Issues #18 #19 e #20
