### ISSUE TITLE
Gráfico de diferentices fica cortado no celular

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#22]
O gráfico de barras que mede o quanto uma cidade recebeu a mais ou a menos fica cortado quando testei no celular.

**Comment by jeffersonrpn** [comment]
Não consegui reproduzir o bug. O corte é na horizontal?

**Comment by luizaugustomm** [comment]
Olha como está no meu celular https://imgur.com/a/dxPUe
