### ISSUE TITLE
Cor de status não muda nas informações da iniciativa

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#23]
Achei em Recife -> Assistência Social.

Existe uma iniciativa que foi concluída (segundo o Governo Federal) e a cor do status é verde no card, mas quando entro nos detalhes da iniciativa, a cor do gráfico e a informação de status estão amarelas.

Sugiro que as cores do gráfico do tempo e o status também mudem de cor.

**Comment by Iararibeiro** [comment]
Rapaz, esse caso não tá acontecendo na aplicação atualmente...Aparece que em Recife não existem iniciativas em assistência social
