### ISSUE TITLE
Colocar mensagem que não há novas mensagens

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#30]
Quando o usuário entrar e ver todas as mensagens do governo, elas desaparecerão, certo?
Então, da próxima vez que ele entrar na página e não houver nenhuma mensagem nova, deveria aparecer uma mensagem do tipo "Não há mensagens novas do governo".

**Comment by soutoam** [comment]
Elas não desapareceram; quando houver uma mensagem nova o ícone do governo vai ter um alerta com um número de acordo com a quantidade de mensagens novas. O usuário vai se guiar pelas datas nas mensagens.
