### ISSUE TITLE
Transição ao mudar de abas na tela de iniciativa está confusa

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#32]
Ao entrarmos na tela de uma iniciativa em particular, temos duas abas: a de detalhes da iniciativa e a de discussões.

Quando clico para ir para a aba de discussões, acontece uma transição como se eu tivesse mudando a página inteira. Não seria melhor uma transição mudando só o conteúdo que está dentro da aba?

**Comment by luizaugustomm** [comment]
O que estou propondo é aproveitar a carcaça da página da iniciativa e ter dois miolos com o conteúdo de cada aba. Até porque, a parte mais externa como título, botão de seguir, etc. devem ser comuns a essas duas páginas.

**Comment by luizaugustomm** [comment]
Tentei mexer nisso e é mais complicado do que parece. Melhor deixar como está.

**Comment by luizaugustomm** [comment]
Não deixei a coisa genérica, mas consegui desativar as transições. \o/

**Comment by ricardoas** [comment]
Pode fechar, @luizaugustomm ????

**Comment by luizaugustomm** [comment]
Pode
