### ISSUE TITLE
Gráfico de tempo/status com comportamento estranho

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#41]
Para chegar a esse erro, faça o seguinte caminho:

Emas -> Assistência Social -> Estruturação da rede de serviços [...](Status: Concluída, segundo a prefeitura)

O gráfico do tempo está errado, já que estamos em 9 jun 2016 e ele ainda está apontando para 30 jan 2015.

![captura de tela de 2016-06-09 13-45-54](https://cloud.githubusercontent.com/assets/475131/15938230/b814753c-2e48-11e6-9492-9beb39ebdba0.png)

**Comment by ricardoas** [comment]
a posição da seta equivale à data atual ou ao status atual?

**Comment by luizaugustomm** [comment]
À data atual. O status nem sempre está de acordo com as datas. Enquanto estas correspondem aos prazos, o status é a situação atual do andamento da iniciativa.

**Comment by Iararibeiro** [comment]
Não seria o status atual? Nesse caso o que fazer quando a iniciativa deveria ter terminado seis meses atrás e ainda está na fase de andamento?

**Comment by luizaugustomm** [comment]
Ou colocar o cursor na última posição do gráfico (no prazo para prestação de contas) e mostrar o status que ainda está em andamento, ou separar essas duas informações.

Minha sugestão é a gente separar a questão do tempo e do status. Esse gráfico seria para indicar o tempo e a gente colocaria o status em outro card ou algo assim.

**Comment by luizaugustomm** [comment]
Fechando pois é duplicada do issue #43
