### ISSUE TITLE
Linha do tempo da iniciativa: ano colado no tic da linha confunde leitor

### ISSUE THREAD

**Issue by nazareno** [luizaugustomm/diferentonas-client#42]
![captura de tela 2016-06-09 as 19 03 05](https://cloud.githubusercontent.com/assets/1053850/15948012/e0fa39f6-2e74-11e6-9cd5-1deae78a3d15.png)

Vide "conclusão", da iniciativa acima de Cajazeiras - PB

**Comment by luizaugustomm** [comment]
Naza, esse problema acontece geralmente em telas menores. Já tinha reportado no Issue #14.
