### ISSUE TITLE
Mostrar a iniciativa com a qual estamos comparando as semelhantes

### ISSUE THREAD

**Issue by nazareno** [luizaugustomm/diferentonas-client#44]
Ao entrar na lista de iniciativas semelhantes, o usuário não vê mais infos da original com a qual ele quer comparar as semelhantes. Sugiro que haja um card com ela nessa tela.

**Comment by Iararibeiro** [comment]
Seria um card fixo que ficaria no topo da lista de semelhantes todo tempo?

**Comment by ricardoas** [comment]
Acho que sim... não tenho outra ideia de como mostrar isso. Agora acho que
tem que de alguma forma destacar que esse é o card da original e não de uma
das similares. Como poderíamos fazer isso?

**Comment by nazareno** [comment]
Pede socorro a Mariana!
