### ISSUE TITLE
Nome da cidade nos detalhes da iniciativa

### ISSUE THREAD

**Issue by nazareno** [luizaugustomm/diferentonas-client#47]
Ao entrar nos detalhes de uma iniciativa não temos hoje a referência de quem que cidade estamos.

**Comment by jeffersonrpn** [comment]
Antes tinha o nome da cidade em todas as sub-telas. Mas no protótipo de Mariana ela colocou o nome do tema ao invés disso. Achas melhor sempre deixar o nome da cidade no topo?

**Comment by nazareno** [comment]
Não precisa ser no topo. Acho que é importante ter, mas não precisa ser lá.
Sugiro ver que padrão outras apps seguem.
Em seg, 13 de jun de 2016 às 12:50, Jefferson Neves <
notifications@github.com> escreveu:

**Comment by Iararibeiro** [comment]
Eu acabei colocando o nome da tela de iniciativas do tema e nos detalhes da iniciativa, vai ficar mesmo ou é para ficar sem?

**Comment by nazareno** [comment]
Não entendi como ficou agora... Cola um print aqui :)

**Comment by Iararibeiro** [comment]
![screenshot from 2016-06-15 13-33-38](https://cloud.githubusercontent.com/assets/3472291/16088641/8524948a-32fe-11e6-9a82-9a549127852e.png)
![screenshot from 2016-06-15 13-34-25](https://cloud.githubusercontent.com/assets/3472291/16088642/8527e96e-32fe-11e6-833c-542fc3526fc3.png)

**Comment by nazareno** [comment]
Pra mim assim está bem legal :)

**Comment by ricardoas** [comment]
Eu tou curtindo essa ideia...
