### ISSUE TITLE
Pesquisar cidade sem distinção de acentuação

### ISSUE THREAD

**Issue by jeffersonrpn** [luizaugustomm/diferentonas-client#5]
A pesquisa deve encontrar cidades digitando-se seu nome com ou sem acentuação.

**Comment by nazareno** [comment]
@joaoarthurbm disse que fez isso no deciframe e que tem a função pronta ;)

**Comment by joaoarthurbm** [comment]
De nada.

```
def remover_combinantes(string):

    string = unicodedata.normalize('NFD', string)

    return u''.join(ch for ch in string if unicodedata.category(ch) != 'Mn')
```

**Comment by nazareno** [comment]
pensei que ia ser nosso primeiro pull request...

**Comment by ricardoas** [comment]
Em python? Faço questão de rejeitar... deve ter nem teste isso! :p

**Comment by luizaugustomm** [comment]
Resolvido por @jeffersonrpn ;)
