### ISSUE TITLE
Verificar carregamento de javascript em algumas versões de android

### ISSUE THREAD

**Issue by jeffersonrpn** [luizaugustomm/diferentonas-client#52]
O app não renderiza as variáveis do Angular.

**Comment by ricardoas** [comment]
Já conseguimos isolar quando isso acontece? Aparentemente a única dica que
temos até agora é aparelhos Sony... alguém sabe como importar uma
configuração de um telefone conhecido no emulador do android? Tou achando
complicadinho... e não consegui fazer nenhum "nexus" abrir o app até agora.

[]'s

**Comment by jeffersonrpn** [comment]
@ricardoas verificou que é problema de uso de funções do JS mais recente em androids com versão inferior a 4.5. Foi atualizado no commit 951d3f616.
