### ISSUE TITLE
Ordenar discussões começando da mais recente

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#53]
Quando posto uma discussão em uma iniciativa, ela vai para o final da lista. Acho que as discussões mais recentes deveriam ser mostradas primeiro.

**Comment by Iararibeiro** [comment]
Adicionando mais coisa: é interessante mostrar a data que a discussão foi lançada.

**Comment by ricardoas** [comment]
isso ainda acontece?????

**Comment by luizaugustomm** [comment]
Sim. Elas só ficam ordenadas quando a página é atualizada. Tem que fazer algo do lado do cliente pra atualizar na hora que fizer um POST.

**Comment by ricardoas** [comment]
era só inserir no início do array ao invés de adicionar no final :p
