### ISSUE TITLE
Problema na filtragem de iniciativas: aparece duplicada

### ISSUE THREAD

**Issue by nazareno** [luizaugustomm/diferentonas-client#55]
Para reproduzir: 

Em Santa Teresinha, PB, veja as iniciativas de Comércio e Serviços e de Gestão Ambiental. Em ambas está a iniciativa "_o Presente Projeto Visa a Construção do Açude Público Primavera, na Comunidade Primavera, no Município de Santa Teresinha¿ pb._". No back-end essa duplicação não acontece: `http://diferentonas.herokuapp.com/cidade/2513802/iniciativas`

**Comment by ricardoas** [comment]
Não consegui reproduzir isso não... em "Comércio e Serviços" só tem a iniciativa: 
"Apoio a Projetos de Infraestrutura Turística - Construção de um Mercado de Artesanato no Município de Santa Teresinha ¿ pb."

**Comment by luizaugustomm** [comment]
Também não consegui reproduzir o bug, @nazareno. Qual versão do app você está utilizando?

**Comment by nazareno** [comment]
Foi a do gh-pages, no sábado.

**Comment by luizaugustomm** [comment]
Pessoal, como não conseguimos reproduzir o bug, estou fechando o issue. :)
