### ISSUE TITLE
1400 Milhões > 1,4 Bilhão

### ISSUE THREAD

**Issue by nazareno** [luizaugustomm/diferentonas-client#6]
Por exemplo, em Recife, o total geral passa de 1000 milhões.

**Comment by ricardoas** [comment]
Nesse caso Recife não deveria estar na média não???

**Comment by nazareno** [comment]
Não entendi a pergunta...
O issue que eu tinha identificado era de formatação: mudar de 1000 milhões pra 1 bilhão.

**Comment by ricardoas** [comment]
Eu tinha entendido sua ">" como "maior que" e achei que a diferentice tava
catalogada errada... me desconsidera!

[]'s
