### ISSUE TITLE
Número de discussões de iniciativa no card ou na info não batem com quantidade de discussões

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#61]
Vá em Pirapemas-MA > Organização Agrária > Recuperação de estrada vicinal [...].
O número de discussões no card e no gráfico de barras na info é igual a 12. No entanto, ao irmos para a aba de discussões, são mostradas apenas 10.

**Comment by Iararibeiro** [comment]
Por que em teoria deveria ser implementado scroll infinito na aba de discussões também, ai o default mostra 10.
