### ISSUE TITLE
Dados não são atualizados ao mudar de tela

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#62]
Vá em qualquer cidade, escolha uma área e escolha uma iniciativa. Siga a iniciativa.
Quando você for na linha do tempo, as atualizações da iniciativa que acabou de ser seguida não irão aparecer. Elas só aparecerão depois que eu dou um refresh na página.

**Comment by luizaugustomm** [comment]
Isso se repete em várias coisas do app. Acho que tudo que é preciso dar POST. @jeffersonrpn tu sabe como resolver isso?

**Comment by Iararibeiro** [comment]
Eu fiz o procedimento e comentei, assim que o comentário é lançado ele já aparece na linha do tempo do usuário.

**Comment by luizaugustomm** [comment]
Também não consegui reproduzir o bug de novo, @Iararibeiro. Fechando o issue.
