### ISSUE TITLE
Textos dos valores nas batalhas não permite comparar bem

### ISSUE THREAD

**Issue by nazareno** [luizaugustomm/diferentonas-client#67]
Há pouco espaço para os textos, e aí não dá pra concluir sobre os valores. 

![image](https://cloud.githubusercontent.com/assets/1053850/16786840/4be98d58-486e-11e6-90d8-128b27b49770.png)

**Comment by Iararibeiro** [comment]
Foi resolvido.
![screenshot from 2016-07-25 18-09-39](https://cloud.githubusercontent.com/assets/3472291/17117660/8f60bd8e-5293-11e6-90d1-0d407e826382.png)

**Comment by luizaugustomm** [comment]
Fecharei.. Caso alguém ache que ela deve ser aberta de novo, pode abrir. ;)
