### ISSUE TITLE
"Recebeu na média" comunica mal

### ISSUE THREAD

**Issue by nazareno** [luizaugustomm/diferentonas-client#7]
"Recebeu na média" quando a cidade recebeu 0 e a média é 1 milhão é difícil de entender. Sugiro mudarmos para "Recebeu valor compatível com as semelhantes". Ou uma versão mais curta disso.

**Comment by ricardoas** [comment]
Tem algum exemplo disso, @nazareno? Tá me cheirando a dados não normais...

**Comment by nazareno** [comment]
Olha Recife.

Para vários dados, as distribuições realmente não são normais. Mas acho que
isso não é um problema. O problema é que na verdade o "na média" é uma
faixa de valores. E como não comunicamos essa faixa nos números na
interface, estou sugerindo comunicarmos em texto, com o "dentro do
esperado".

**Comment by nazareno** [comment]
Explicando mais: o "dentro do esperado" pode ser entre 10 e 20 milhões, pra uma área onde o recebido pelas cidades semelhantes varia muito, e varia dentro dessa faixa. Mas o usuário pode estranhar porque em algumas áreas é receber 5 milhões a menos que outra cidade é normal, e em outras receber 500 mil a menos é "bem menos".

**Comment by ricardoas** [comment]
Brainstorm:

Campina Grande:
- "recebeu ([muito] + mais/menos) que suas semelhantes" <= atual
- "se destaca positivamente/negativamente nos investimentos para/de
  <ação>"
- "não se destaca nos investimentos para/de <ação>"
- "tem um [forte] destaque positivo/negativo nos investimentos para/de
  <ação>"

:)

2016-05-25 14:58 GMT-03:00 nazareno notifications@github.com:

**Comment by nazareno** [comment]
eu não acho que tem problema com as frases tirando a "na média". 
nova sugestão de solução: tudo como está, em vez de "na média" colocamos "dentro do esperado" e em vez de colocar a média das cidades semelhantes colocamos a faixa de valores que definimos como "dentro do esperado". em vez de X milhões ficaria X - Y milhões.

**Comment by ricardoas** [comment]
Gostei...

2016-05-28 0:05 GMT-03:00 nazareno notifications@github.com:

**Comment by jeffersonrpn** [comment]
Acredito que esta issue está fechada. Confirma aí @luizaugustomm .

**Comment by luizaugustomm** [comment]
Fechada! 😃

**Comment by nazareno** [comment]
oi pessoal. vocês podiam dar opinião sobre essa sugestão que fiz ali em cima? 

> nova sugestão de solução: tudo como está, em vez de "na média" colocamos "dentro do esperado" e em vez de colocar a média das cidades semelhantes colocamos a faixa de valores que definimos como "dentro do esperado". em vez de X milhões ficaria X - Y milhões.

**Comment by luizaugustomm** [comment]
Naza, eu modifiquei para "dentro do esperado". Comunicou melhor mesmo. Por isso eu tinha fechado a issue. Mas essa parte do intervalo de valores na média, não fiz. Não ficaria meio inconsistente ter um card de dois jeitos? Sugiro mudar só a frase, pelo menos por enquanto.

**Comment by nazareno** [comment]
Quais os dois jeitos?

Minha sugestão é que em todos os cards de área, independente do que esteja
escrito, no lugar de ter a média que hoje temos, existam dois valores que
delimitam um intervalo.

Caso concordemos que essa é a melhor alternativa, seria  necessário
primeiro mudar o backend pra prover essa info, e depois na interface.

**Comment by luizaugustomm** [comment]
Pensei que teria um card mostrando na média, e outro tipo de card mostrando um intervalo.

No caso de mudar isso para todos os cards, ficaria bacana.

Como seria definido esse intervalo? Já tem uma ideia?

**Comment by nazareno** [comment]
Ele já é calculado hoje. Só não é retornado. Deixa ver o que os outros
acham.

**Comment by ricardoas** [comment]
Não consigo opinar...

**Comment by luizaugustomm** [comment]
E aí, o que decidimos dessa issue? Seria massa a gente colocar o intervalo ao invés da média. Não tem como retornar ele fácil na API, Naza? Aí a gente poderia ver se fica bom.

**Comment by luizaugustomm** [comment]
Feito! Ficou bem mais fácil de entender! Parabéns, pessoal. :)
