### ISSUE TITLE
Iniciativa atualizada que não está atualizada

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#70]
As informações de atualização das datas de uma iniciativa (e.g. data de conclusão) estão com um problema. Tanto o valor anterior quanto o atual são os mesmos.

Pegue o exemplo de Anhaembi-SP. Vá em Desporto e Lazer->Novidades. Preste atenção que todas as datas anteriores e atuais são iguais. Isso é um problema do backend, @ricardoas.

**Comment by luizaugustomm** [comment]
![iniciativa-atualizada-bug](https://cloud.githubusercontent.com/assets/475131/17178289/40482710-53eb-11e6-93ed-d350cb3484d3.png)

**Comment by ricardoas** [comment]
Tenho impressão que isso acontece devido à precisão da data... vou
modificar no backend pra comparar apenas dia/mês/ano
