### ISSUE TITLE
Valores NA no status da iniciativa

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#72]
![status](https://cloud.githubusercontent.com/assets/475131/17178909/a44ca5a4-53ed-11e6-89a9-30ba5dd881a6.png)

**Comment by Iararibeiro** [comment]
Os valores recebidos do servidor:
Object { id: 794924, ano: 2013, titulo: "Apoio a Projeto de Infraestrutura T…", programa: "Turismo", area: "Comércio e Serviços", fonte: "Ministerio do Turismo", concedente: "MINISTERIO DO TURISMO", status: "NA", temAditivo: false, verbaGovernoFederal: 631492.375, 11 more… }

**Comment by ricardoas** [comment]
a backend fez uma atualização com um arquivo inválido e inseriu os NA, estou repopulando o banco pra a gente reavaliar isso, @Iararibeiro
