### ISSUE TITLE
Gráfico de linha do tempo sem funcionar

### ISSUE THREAD

**Issue by Iararibeiro** [luizaugustomm/diferentonas-client#73]
O layout do gráfico tá todo bagunçando e precisa sincronizar com o layout de mariana.

**Comment by ricardoas** [comment]
update: ficou assim depois de corrigir os NAs no BD, @Iararibeiro 

![screenshot from 2016-07-27 14-09-05](https://cloud.githubusercontent.com/assets/311029/17184726/28f2a464-5404-11e6-9256-2ecc174c3459.png)

**Comment by Iararibeiro** [comment]
Bruxaria, valha. 
Mas faz sentido, tudo está relacionado ao status da iniciativa. thanks @ricardoas
