### ISSUE TITLE
Dar joinha no próprio card

### ISSUE THREAD

**Issue by luizaugustomm** [luizaugustomm/diferentonas-client#76]
Quando o usuário estiver na linha do tempo e clicar no joinha ou no ¬joinha, ele já era pra ficar de outra cor de ficar contabilizado.

Isso já está planejado para ser feito, @Iararibeiro ?

**Comment by Iararibeiro** [comment]
Eu vou conferir @luizaugustomm eu quando fiz essa parte deixei as funções mais ou menos prontas.

**Comment by ricardoas** [comment]
eu ainda não juntei as funções do backend com o frontend ainda não...
inclusive percebi que falta vir a contagem do backend... estou adicionando.
