### ISSUE TITLE
problema na busca por cidades

### ISSUE THREAD

**Issue by ricardoas** [luizaugustomm/diferentonas-client#8]
Estamos com um problema no sort das cidades na tela de busca.
Ex: Existem duas cidades São Pedro, uma em RN e outra em SP. Quando eu entro com "São Pedro" na tela de busca, aparecem várias outras "São Pedro d*" antes da "São Pedro - RN" e a de SP nem chega a aparecer!

**Comment by luizaugustomm** [comment]
Resolvido no último commit por @jeffersonrpn ;)
