### ISSUE TITLE
app não mostra nada quando cidades não tem "diferentices" na média

### ISSUE THREAD

**Issue by ricardoas** [luizaugustomm/diferentonas-client#9]
Ex: Recife não tem nenhuma área cinza... quando clico no botão deveria aparecer alguma mensagem de "Não há áreas nessa categoria"

**Comment by luizaugustomm** [comment]
Acho que seria melhor ocultar o botão ver todos nesse caso, @ricardoas. Já que não teria mais áreas para ver. O que acha?

**Comment by ricardoas** [comment]
Concordo...
